SN1-543 - SN1-523 - refactor metadata validator/miner, remove run_id, remove block_check synapses and functions
blockchain-insights/blockchain-data-subnet pull request #164
Opened 2024-04-01 18:09 UTC by 0xMarx

2024-04-01 19:46 UTC, wendellswa06 approved these changes

2024-04-01 19:46 UTC, wendellswa06 approved these changes

2024-04-01 20:20 UTC, aph5nt requested changes

2024-04-01 20:20 UTC, aph5nt commented on neurons/storage.py
> +        subtensor = self.subtensor
did you test that? I tried and it did not work

2024-04-01 20:20 UTC, aph5nt commented on neurons/storage.py
> +        subtensor = bt.subtensor(config=self.config)
did you test that? I tried and it did not work

2024-04-02 19:08 UTC, aph5nt approved these changes

2024-04-02 19:09 UTC, merged