Sn1 117/move offline indexer to the main project
blockchain-insights/blockchain-data-subnet pull request #80
Opened 2024-02-11 20:44 UTC by aph5nt

2024-02-12 21:28 UTC, aph5nt commented on neurons/nodes/bitcoin/node.py
i see, how much disk are taking those pickles? maybe we could have them splited into multimple files and load pickled on demand? im thinking about some easo of use or miners

2024-02-12 21:29 UTC, aph5nt commented on neurons/nodes/bitcoin/node.py
another question... will it be still easy for you to use it without docker ?

2024-02-12 21:32 UTC, ronnie-samaroo commented on neurons/nodes/bitcoin/node.py
![image](https://github.com/blockchain-insights/blockchain-data-subnet/assets/77883042/042ddbcf-63c2-4a38-842d-863c8ec7ef48)

2024-02-12 21:32 UTC, ronnie-samaroo commented on neurons/nodes/bitcoin/node.py
> another question... will it be still easy for you to use it without docker ?

yes, it's easy to use without docker.

2024-02-12 21:36 UTC, ronnie-samaroo commented on neurons/nodes/bitcoin/node.py
I think we can load pickles dynamically at runtime so users just need to specify a single directory.

2024-02-19 14:10 UTC, ronnie-samaroo approved these changes

2024-02-19 14:32 UTC, 0xMarx requested changes

2024-02-19 14:32 UTC, 0xMarx commented on neurons/nodes/bitcoin/btc-vout-hashtable-builder/utils.py
> +def get_sub_keys():
duplicate method node_utils get_tx_out_hash_table_sub_keys()

2024-02-21 14:28 UTC, 0xMarx approved these changes

2024-02-21 14:29 UTC, merged