[SN-93] Synapse query
blockchain-insights/blockchain-data-subnet pull request #87
Opened 2024-02-16 21:43 UTC by nnboskovic

Added an implementation for running a read cypher query on a synapse

@aph5nt @0xMarx Let me know what the best way to test this would be

2024-02-16 22:15 UTC, 0xMarx requested changes

2024-02-16 22:15 UTC, 0xMarx commented on neurons/miners/bitcoin/funds_flow/graph_search.py
> +    def execute_cypher_query(self, query):
does this work? it should be call with mandatory `terms` parameter no?

2024-02-16 22:15 UTC, 0xMarx commented on neurons/miners/miner.py
> +            forward_fn=self.cypher_query,
the cypher query is the query endpoint, you should implement the `query()` function

2024-02-16 22:15 UTC, 0xMarx commented on neurons/miners/miner.py
> +        ))
the parentheses () are not needed in this case

2024-02-16 22:15 UTC, 0xMarx commented on neurons/utils.py
> +def is_potentially_malicious(query, terms):
is_malicious is better then is_potentially_malicious as a function name

2024-02-16 22:15 UTC, 0xMarx commented on neurons/miners/bitcoin/funds_flow/graph_search.py
> +    def execute_cypher_query(self, query):
also `execute_query` should be the name as we won't execute any other type of query.

2024-02-20 12:45 UTC, ronnie-samaroo approved these changes
good enough for MVP

2024-02-20 12:50 UTC, merged