SN-156 - False positive for validator cross check
blockchain-insights/blockchain-data-subnet pull request #94
Opened 2024-02-22 15:57 UTC by nnboskovic

Previous validator check could give a false positive for start_block_height == 0

2024-02-22 17:11 UTC, StormyTalents approved these changes

2024-02-22 17:11 UTC, StormyTalents commented on neurons/validators/validator.py
Good catcha👍, we always should consider writing try-exception clause for the extremely bad situations tho they rarely happen to occur. 💯

2024-02-22 17:17 UTC, StormyTalents reviewed
Can fix the git test fail btw?

2024-02-23 11:53 UTC, aph5nt requested changes

2024-02-23 11:53 UTC, aph5nt commented on neurons/validators/validator.py
but what exception can happen here ??

2024-02-23 11:53 UTC, aph5nt commented on neurons/validators/validator.py
we need to try catch calls to btcnode

2024-02-25 21:57 UTC, aph5nt commented
it was implemented in other PR based on this one

2024-02-25 21:57 UTC, closed without merging