Node blockchain headers call
blockchain-insights/blockchain-data-subnet pull request #95
Opened 2024-02-22 17:22 UTC by nnboskovic

Added a blockchain headers call for future validator use to check how out of sync the local node is

2024-02-22 17:29 UTC, StormyTalents requested changes
Very close to merge 👍

Small CR
Can attach the snapshot on this PR desc, which shows it works well out to get block_height

2024-02-25 21:56 UTC, aph5nt commented
> Very close to merge 👍
> 
> Small CR Can attach the snapshot on this PR desc, which shows it works well out to get block_height

which snapshout you mean ?

2024-03-04 12:13 UTC, StormyTalents approved these changes

2024-03-04 12:16 UTC, StormyTalents commented
> > Very close to merge 👍
> > Small CR Can attach the snapshot on this PR desc, which shows it works well out to get block_height
> 
> which snapshout you mean ?

PR was changed? i asked about `get block_height` 2 weeks ago, now its not related to block_height. weird.
btw approved

2024-03-14 08:50 UTC, closed without merging